$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: .
command: python train.py
inputs:
  input_data: 
    path: azureml:MASBJK_:1
environment:
  name: stock-prediction-env
  conda_file: custom_env.yml
  image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:latest
compute: azureml:cpu-cluster
experiment_name: stock-price-prediction
description: Train a PyTorch LSTM model for stock price prediction
