$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: .
command: python train.py
inputs:
  input_data: 
    path: azureml:MASBJK_:1
environment: azureml:AzureML-pytorch-1.10-ubuntu18.04-py38-cuda11-gpu@latest
compute: azureml:cpu-cluster
experiment_name: stock-price-prediction
description: Train a PyTorch LSTM model for stock price prediction
