name: Data Upload to Azure ML
env:
  ticker: MASB.JK
  start: 2020-01-01
  end: 2023-12-31
  AZURE_RESOURCE_GROUP: bramastyaz-rg
  AZURE_ML_WORKSPACE: mlops-thesis
on:
  schedule:
    - cron: "1 1 * *1"
  workflow_dispatch:
  push:
    paths:
      - 'jobs/data_download.py'
      - 'jobs/update_training_yamls.py'
      - '.github/workflows/data_pipeline.yml'
jobs:
  datawork:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with: 
        python-version: "3.9"
    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install numpy==1.23.5 pandas==1.5.3 yfinance==0.2.18 pyyaml
    - name: Download ticker data and update YAML file
      run: python data_download.py --ticker ${{ env.ticker }} --start ${{ env.start }} --end ${{ env.end }}
      working-directory: jobs
    - name: Print data_upload.yml contents
      run: |
        echo "Contents of data_upload.yml:"
        cat data_upload.yml
      working-directory: jobs
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    - name: Install Azure ML CLI extension
      run: |
        az version
        az extension add -n ml -y
    - name: Update Azure ML data asset
      run: |
        az version
        az extension list
        az ml -h
        echo "Resource Group: ${{ env.AZURE_RESOURCE_GROUP }}"
        echo "Workspace: ${{ env.AZURE_ML_WORKSPACE }}"
        echo "Contents of data_upload.yml:"
        cat data_upload.yml
        az ml data update --name MASBJK_data --path ./data/MASBJK --type mltable --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --workspace-name ${{ env.AZURE_ML_WORKSPACE }}
      working-directory: jobs
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update data files" && git push)
