name: Model Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 1"  # Runs at 1 AM every Monday

env:
  AZURE_RESOURCE_GROUP: bramastyaz-rg
  AZURE_ML_WORKSPACE: mlops-thesis

jobs:
  data-and-train:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy pyyaml

      - name: Download data
        run: python jobs/data_download.py

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure ML CLI
        run: |
          az extension add -n ml -y

      - name: Upload data to Azure
        run: |
          az ml data create -f jobs/data_upload.yml \
                            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
                            --workspace-name ${{ env.AZURE_ML_WORKSPACE }}

    # Add steps for model training here
    # For example:
    # - name: Train model
    #   run: python train.py

    # Add steps for model evaluation and registration here
