name: Model Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 1'  # Runs at 1 AM every Monday

env:
  AZURE_RESOURCE_GROUP: bramastyaz-rg
  AZURE_ML_WORKSPACE: mlops-thesis

jobs:
  train-and-register:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Azure ML CLI
        run: |
          az extension add -n ml -y
          az configure --defaults group=${{ env.AZURE_RESOURCE_GROUP }} workspace=${{ env.AZURE_ML_WORKSPACE }}

      - name: Train Model
        run: |
          az ml job create --file jobs/train.yml --debug
